### ISSUE TITLE
Spread operator expects a newline in REPL

### ISSUE THREAD

**Issue by pixelpax** [maxogden/node-repl#10]
Using node 6.4.0 REPL on macOS 10.12.3

I am expecting to be able to use the spread operator to copy an object. Instead, node thinks that I need to enter more lines of code for the statement to be complete. 

If this operation is not yet supported, I would expect an error message. 

```
> a = {d:0, e:0}
{ d: 0, e: 0 }
> b = {e:1, f:1}
{ e: 1, f: 1 }
> c  = {...a}
... 
... 
```

**Comment by ed-g** [comment]
@pixelpax looks like that's still in the candidate stage: http://kangax.github.io/compat-table/esnext/#test-object_spread_properties

**Comment by crobinson42** [comment]
@pixelpax this doesn't appear to be an issue any longer - want to check and close this issue?

**Comment by pixelpax** [comment]
Ah, thanks for the poke. Glad to see it's resolved :D
