### ISSUE TITLE
Example with CoffeeScript

### ISSUE THREAD

**Issue by aleclarson** [maxogden/node-repl#5]
A customizable `eval` was mentioned in your blog post. Is this not yet setup?

I also noticed that `index.js` is missing, so I'm assuming this isn't ready for public use quite yet?

**Comment by max-mapper** [comment]
`node-repl` is a CLI tool, we have not implemented a node API. In my blog post it states

> The node repl supports passing in a custom eval function

notice it is 'the node repl' and not 'node-repl' (which is why it links to https://iojs.org/api/repl.html#repl_repl_start_options)

there is no index.js because it's only a CLI tool at the moment

**Comment by aleclarson** [comment]
Thanks for the clarification!
