### ISSUE TITLE
Pointless module?

### ISSUE THREAD

**Issue by ghost** [maxogden/node-repl#7]
This functionality is provided by the repl module already:

``` shell
node -e "require('repl').start('> ').parseREPLKeyword('load','file.js')"
```

**Comment by max-mapper** [comment]
@aynik you can programmatically load `node-repl` inside any scope you want repl access to in a program. the method you shared only works for the outermost scope. also it's not pointless to have easy to use CLI tools

**Comment by jainprash** [comment]
@maxogden - I just came upon this discussion, and wanted to learn, how to programmatically load node-repl inside inner scope, so that I can have more access to inner variables. Thanks!
